[package]
name = "encoder_validation"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "=0.25.8", default-features = false, features = ["jpeg", "png"] }
fast_image_resize = { version = "=6.1.0", features = ["image"] }
serde_json = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
